USE SAMPLE_DATA;

SELECT * FROM sample_data_1;

SELECT COUNT(ORDERID) as Total_order, 
ROUND(SUM(SALES),2) AS TOTAL_SALES, 
ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT,
ROUND(SUM(SALES*PROFIT),2)AS REVENUE FROM sample_data_1;

SELECT customerName,
ROUND(SUM(sales),2) AS SALES,
ROUND(SUM(profit),2) AS PROFIT FROM sample_data_1
GROUP BY CUSTOMERNAME ORDER BY SUM(SALES) DESC LIMIT 10;


SELECT count(distinct CUSTOMERNAME)as Total_customers 
FROM sample_data_1;

SELECT DISTINCT STATE FROM sample_data_1;

SELECT REGION, COUNT(distinct STATE) as States,round(sum(sales),2) as Total_sales FROM sample_data_1
GROUP BY REGION ORDER BY round(sum(sales),2) DESC;

SELECT STATE, MAX(SALES) MAX_SALES FROM sample_data_1
GROUP BY STATE ORDER BY MAX(SALES) DESC;

SELECT STATE,MIN(SALES) MIN_SALES FROM sample_data_1
GROUP BY STATE ORDER BY MIN(SALES) ASC;

select * FROM sample_data_1;

SELECT SEGMENT,CUSTOMERNAME FROM sample_data_1;

SELECT SEGMENT, COUNT(DISTINCT CUSTOMERNAME) AS TOTAL_CUSTOMERS FROM sample_data_1
GROUP BY SEGMENT;

SELECT REGION,COUNT(DISTINCT CUSTOMERNAME) AS TOTAL_CUSTOMERS FROM sample_data_1
GROUP BY REGION ORDER BY 2 DESC;

SELECT STATE, COUNT(DISTINCT CUSTOMERNAME) AS TOTAL_CUSTOMERS FROM sample_data_1
GROUP BY STATE ORDER BY COUNT(CustomerName) DESC;


SELECT * FROM sample_data_1;


SELECT OrderPriority,COUNT(CUSTOMERNAME) AS TOTAL_CUSTOMERS FROM sample_data_1
GROUP BY 1 ORDER BY 2 DESC;

SELECT PRODUCTNAME,
ROUND(MAX(SALES),0)RATE FROM sample_data_1
GROUP BY PRODUCTNAME ORDER BY 2 DESC LIMIT 10;


SELECT CUSTOMERNAME,SHIPMODE,PRODUCTNAME,SUM(QUANTITY) QUANTITY FROM sample_data_1
WHERE STATE = "MAHARASHTRA" AND SHIPMODE = "REGULAR AIR"
GROUP BY CUSTOMERNAME, SHIPMODE,PRODUCTNAME
ORDER BY QUANTITY DESC LIMIT 10;


SELECT SUM(QUANTITY) AS TOTAL_ORDERS,
ROUND(SUM(SALES),2) AS TOTAL_SALES,
ROUND(SUM(PROFIT),2) AS TOTAL_PROFIT
 FROM sample_data_1;
 
 
 SELECT DISTINCT CUSTOMERNAME,STATE,REGION,PRODUCTNAME,SUM(SALES) FROM sample_data_1 
  WHERE STATE = "HARYANA" AND REGION = "NORTH" 
   GROUP BY CUSTOMERNAME,STATE,REGION,PRODUCTNAME;

#REMOVING THE DUPLICATE 
#CUSTOMER NAME AND PRODUCT NAME BOTH HAVING THE DUPLICATE
# WITH CTE

WITH SAMPLE_CTE AS (
SELECT CUSTOMERNAME,
ROW_NUMBER() OVER(PARTITION BY CUSTOMERNAME, ORDERID ORDER BY CUSTOMERNAME)
AS ROW_NUM FROM sample_data_1 
) SELECT * FROM SAMPLE_CTE WHERE ROW_NUM >1;


#text function 
SELECT upper(CUSTOMERNAME) AS CUSTOMER_NAME FROM sample_data_1;

#REGION WISE REVENUE 
#sub-query
SELECT * FROM
(SELECT REGION,ROUND(SUM(SALES*QUANTITY),2) AS REGIONAL_REVENUE FROM SAMPLE_DATA_1
GROUP BY REGION) AS REGIONAL_REVENUE  
ORDER BY REGIONAL_REVENUE DESC;


#REGION WISE SALES
SELECT * FROM
(SELECT REGION,ROUND(SUM(SALES),2) AS REGIONAL_SALES FROM SAMPLE_DATA_1
GROUP BY REGION) AS REGIONAL_SALES  
ORDER BY REGIONAL_SALES DESC;



#FILTER ORDERPRIORITY AS LOW
select * from sample_data_1
where orderpriority = (select distinct OrderPriority from sample_data_1 
where OrderPriority = "low");


#TOTAL NUMBERS OF STATE AND TOTAL PRODUCTS 
SELECT count(distinct state) AS TOTAL_STATES,
COUNT(DISTINCT PRODUCTNAME) AS TOTAL_PRODUCT
FROM SAMPLE_DATA_1;

#APPLY SOME FILTERS 
SELECT CUSTOMERNAME, CITY, STATE, ORDERPRIORITY, REGION, PRODUCTNAME, PRODUCTCONTAINER, SHIPMODE
FROM SAMPLE_DATA_1
WHERE ORDERPRIORITY = 'LOW' AND SHIPMODE = 'REGULAR AIR';

SELECT * FROM sample_data_1;

#TOP 10 EXPENSIVE PRODUCT 
SELECT DISTINCT PRODUCTNAME, SALES FROM sample_data_1
ORDER BY SALES DESC LIMIT 10;

#TOP 10 CHEAPEST PRODUCT 
SELECT DISTINCT PRODUCTNAME,SALES AS SALES  FROM SAMPLE_DATA_1
ORDER BY SALES ASC LIMIT 10;

select * from sample_data_1;



